title: 'kiranramanna.github.io'
description: "Research and personal blog on various learnings."
baseurl: "/thoughts"
url: "https://kiranramanna.github.io"

header_pages:
  - index.md
  - kiranramanna.md
  - about.md

# #style: light # dark (default) or light
style: hacker

footer: 'follow me on <a href="https://www.linkedin.com/in/kiranramanna/">linkedin</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
